name: helm-release
on:
  workflow_dispatch:

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access

env:
  OWNER_NAME: ${{ github.repository_owner }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Helm OCI
        run: |
          VERSION=$(yq e '.version' charts/tf-controller/Chart.yaml)
          mkdir helm-release
          helm package charts/tf-controller/ -d helm-release
          helm push helm-release/tf-controller-${VERSION}.tgz oci://ghcr.io/${{ env.OWNER_NAME }}/charts
